Creative-mode timer
biothings/bte_trapi_query_graph_handler pull request #193
Opened 2024-05-02 23:23 UTC by rjawesome

https://github.com/biothings/biothings_explorer/issues/808
Switches result-limit in creative mode for a limit based on estimated completion time of templates.

2024-05-03 18:04 UTC, tokebe requested changes
Made a few notes on desired behavior, please review and make the appropriate changes.

2024-05-03 18:04 UTC, tokebe commented on src/inferred_mode/inferred_mode.ts
> +          `Final result count: ${Object.keys(combinedResponse.message.results).length}`,
We still want to log how many results before/after truncation

2024-05-03 18:04 UTC, tokebe commented on src/inferred_mode/inferred_mode.ts
> -    response.message.results = response.message.results.slice(0, this.CREATIVE_LIMIT);
Results should still be truncated to the top 500 at the end per Translator expectations.

2024-05-03 18:04 UTC, tokebe commented on src/inferred_mode/inferred_mode.ts
> -    this.CREATIVE_LIMIT = process.env.CREATIVE_LIMIT ? parseInt(process.env.CREATIVE_LIMIT) : 500;
Creative limit should be kept, but used only for truncation, rather than as a stopping threshold

2024-05-04 01:52 UTC, rjawesome commented
Creative limit results truncation has been added back.

2024-08-19 18:43 UTC, tokebe commented
Closing as parent issue is superseded

2024-08-19 18:43 UTC, closed without merging